"""contact and tags tables

Revision ID: 74e076066720
Revises: 
Create Date: 2020-02-09 19:29:55.923488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e076066720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('ContactId', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=64), nullable=True),
    sa.Column('LastName', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Phone', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('ContactId')
    )
    op.create_index(op.f('ix_contact_ContactId'), 'contact', ['ContactId'], unique=True)
    op.create_table('tag',
    sa.Column('TagId', sa.Integer(), nullable=False),
    sa.Column('TagName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('TagId')
    )
    op.create_table('contact_tag',
    sa.Column('ContactTagId', sa.Integer(), nullable=False),
    sa.Column('TagId', sa.Integer(), nullable=True),
    sa.Column('ContactId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ContactId'], ['contact.ContactId'], ),
    sa.ForeignKeyConstraint(['TagId'], ['tag.TagId'], ),
    sa.PrimaryKeyConstraint('ContactTagId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_contact_ContactId'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
